[build]
command = "npm i -g xyd-js && npm run build:docs"
publish = ".xyd/build/client"

[[redirects]]
from = "/"
to = "/docs/getting-started"
status = 301
force = true

[[redirects]]
from = "/index.html"
to = "/docs/getting-started"
status = 301
force = true
